dist: trusty
sudo: required

language: scala

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
    - master
    - ImpersonationSpike

notifications:
  email: false

install:
  - . ./bin/install-spark.sh
  # Build the SQL server for following unit tests
  - ./build/mvn -q clean package -DskipTests

script:
  # - ENABLE_FAULT_TOLERANCE_TESTS=1 ./build/mvn -q scalastyle:check test
  # - travis_wait 360 ./build/mvn -q scalastyle:check test
  - ./build/mvn -q scalastyle:check test

after_success:
  # Fails because of too long tests in Travis CI
  # - ./build/mvn -q cobertura:cobertura coveralls:report

